import { Signal, Tag } from "./types";

export const ALL_TAGS: Tag[] = [
  { id: "t1",  name: "IA Generativa",            color: "#8b5cf6", category: "technology" },
  { id: "t2",  name: "Sostenibilidad",            color: "#10b981", category: "theme" },
  { id: "t3",  name: "Trabajo Futuro",            color: "#f59e0b", category: "theme" },
  { id: "t4",  name: "Salud Digital",             color: "#ef4444", category: "sector" },
  { id: "t5",  name: "Geopolítica",               color: "#6366f1", category: "theme" },
  { id: "t6",  name: "Finanzas Descentralizadas", color: "#0ea5e9", category: "sector" },
  { id: "t7",  name: "Bienestar",                 color: "#ec4899", category: "theme" },
  { id: "t8",  name: "Educación",                 color: "#14b8a6", category: "sector" },
  { id: "t9",  name: "Horizonte 2030",            color: "#f97316", category: "horizon" },
  { id: "t10", name: "Horizonte 2040",            color: "#a855f7", category: "horizon" },
  { id: "t11", name: "Movilidad",                 color: "#84cc16", category: "sector" },
  { id: "t12", name: "Privacidad",                color: "#64748b", category: "theme" },
  { id: "t13", name: "Infraestructura",           color: "#f59e0b", category: "sector" },
  { id: "t14", name: "Espacios Públicos",         color: "#22c55e", category: "sector" },
  { id: "t15", name: "Transporte Urbano",         color: "#3b82f6", category: "sector" },
  { id: "t16", name: "Smart City",                color: "#a855f7", category: "technology" },
];

export const MOCK_SIGNALS: Signal[] = [
  {
    id: "s1",
    title: "LLMs superan a médicos residentes en diagnóstico de patologías raras",
    imageUrl: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&q=80",
    sources: [
      { label: "Nature Medicine, 2026", url: "https://www.nature.com/nm" },
      { label: "Stanford HAI Report 2025", url: "https://hai.stanford.edu" },
    ],
    observation: "Modelos de lenguaje entrenados con datos clínicos superan en un 12% la precisión diagnóstica de médicos residentes en enfermedades raras. El estudio abarca 14 hospitales en 6 países y 80.000 casos.",
    whySignal: "Por primera vez, la IA no asiste al médico: lo supera en una tarea cognitiva nuclear. Esto rompe el paradigma de la IA como herramienta de apoyo y plantea un nuevo rol para el profesional sanitario como intérprete y validador, no como diagnosticador primario.",
    implication: "Si esto se vuelve masivo, el banco deberá revisar sus productos de seguro de salud y la valoración de activos en clínicas. Abre además una oportunidad de financiación verde para hospitales que adopten IA diagnóstica, con impacto directo en la cartera de crédito corporativo del sector salud.",
    type: "technology",
    strength: "strong",
    tags: [ALL_TAGS[0], ALL_TAGS[3], ALL_TAGS[8]],
    votes: 24,
    userVoted: false,
    authorName: "Elena Martín",
    authorInitials: "EM",
    createdAt: "2026-05-12T09:30:00Z",
    updatedAt: "2026-05-12T09:30:00Z",
    comments: [
      { id: "c1", signalId: "s1", authorName: "Carlos López", authorInitials: "CL", content: "Habría que cruzarla con las tendencias regulatorias en la UE sobre IA médica.", createdAt: "2026-05-12T10:15:00Z" },
      { id: "c2", signalId: "s1", authorName: "Ana Torres", authorInitials: "AT", content: "El 12% es significativo pero el contexto importa. ¿Solo residentes o también especialistas?", createdAt: "2026-05-12T11:00:00Z" },
    ],
  },
  {
    id: "s2",
    title: "Francia prohíbe vuelos domésticos con alternativa ferroviaria inferior a 4 horas",
    sources: [
      { label: "Le Monde, abril 2026", url: "https://www.lemonde.fr" },
      { label: "Reuters Climate Policy Tracker" },
      { label: "Comisión Europea — Directiva de movilidad sostenible" },
    ],
    observation: "Francia amplía su veto a vuelos domésticos a todas las rutas con tren de menos de 4 horas. Otros 6 países europeos debaten legislación equivalente. Afecta a más de 40 rutas y 12 millones de pasajeros anuales.",
    whySignal: "No es una medida voluntaria ni un incentivo fiscal: es una prohibición directa. Marca el inicio de una regulación punitiva sobre la movilidad de alto carbono, algo inédito en democracias occidentales. La presión política para extenderlo a nivel europeo crece rápidamente.",
    implication: "Si esto se extiende a toda la UE, el banco deberá provisionar riesgo en su cartera de financiación a aerolíneas regionales y aeropuertos. Simultáneamente, se abren oportunidades concretas de bono verde para infraestructura ferroviaria y productos de inversión ESG vinculados a movilidad baja en carbono.",
    type: "social",
    strength: "strong",
    tags: [ALL_TAGS[1], ALL_TAGS[4], ALL_TAGS[10], ALL_TAGS[8]],
    votes: 31,
    userVoted: true,
    authorName: "David Ruiz",
    authorInitials: "DR",
    createdAt: "2026-05-11T14:20:00Z",
    updatedAt: "2026-05-11T14:20:00Z",
    comments: [
      { id: "c3", signalId: "s2", authorName: "Isabel Gómez", authorInitials: "IG", content: "Los patrones de viaje de negocio van a cambiar radicalmente. Impacto en las tarjetas corporate.", createdAt: "2026-05-11T16:30:00Z" },
    ],
  },
  {
    id: "s3",
    title: "El 40% de los freelancers globales usan IA como su 'empleado virtual' principal",
    sources: [
      { label: "Upwork Future Workforce Report 2026", url: "https://www.upwork.com/research" },
      { label: "McKinsey Global Institute — The Augmented Worker" },
    ],
    observation: "Upwork documenta que 4 de cada 10 trabajadores independientes delegan sistemáticamente tareas cognitivas a herramientas de IA, facturando hasta un 60% más sin aumentar sus horas trabajadas. Emerge una nueva clase: el trabajador aumentado.",
    whySignal: "La IA ya no es una ventaja competitiva para el freelancer: es infraestructura básica. Esto crea una bifurcación brutal en el mercado laboral entre quienes la adoptan y quienes no, y difumina la frontera entre trabajo humano y automatizado en la economía de servicios.",
    implication: "Si esto se vuelve masivo, el modelo de scoring crediticio para autónomos queda obsoleto. El banco debe rediseñar sus productos de financiación para el trabajador aumentado: ingresos más volátiles pero con mayor capacidad de escala, algo que los modelos actuales de riesgo no capturan.",
    type: "foresight",
    strength: "medium",
    tags: [ALL_TAGS[0], ALL_TAGS[2], ALL_TAGS[8]],
    votes: 18,
    userVoted: false,
    authorName: "Marta Sanz",
    authorInitials: "MS",
    createdAt: "2026-05-10T08:00:00Z",
    updatedAt: "2026-05-10T08:00:00Z",
    comments: [],
  },
  {
    id: "s4",
    title: "Interfaces neuronales no invasivas alcanzan 200 palabras por minuto sin cirugía",
    sources: [
      { label: "MIT Technology Review, marzo 2026", url: "https://www.technologyreview.com" },
      { label: "Neurosity — EEG Consumer Report" },
    ],
    observation: "Una startup californiana logra transcribir pensamiento a texto a 200 palabras por minuto usando un headband EEG de consumo. Requiere entrenamiento personal de 2 horas. Precio estimado de lanzamiento: 400 USD.",
    whySignal: "Elimina la barrera quirúrgica de las interfaces neuronales. Por primera vez existe un camino realista hacia la interacción humano-ordenador sin pantalla ni teclado, accesible al consumidor masivo. La curva de adopción podría ser más rápida que la del smartphone.",
    implication: "Si esto se vuelve masivo en 2035-2040, el banco deberá rediseñar toda su UX desde cero. La autenticación biométrica neural podría reemplazar contraseñas y biometría facial. Señal de vigilancia estratégica: invertir hoy en explorar aplicaciones para banca sin fricción.",
    type: "technology",
    strength: "weak",
    tags: [ALL_TAGS[0], ALL_TAGS[3], ALL_TAGS[9]],
    votes: 9,
    userVoted: false,
    authorName: "Pablo Herrera",
    authorInitials: "PH",
    createdAt: "2026-05-09T11:45:00Z",
    updatedAt: "2026-05-09T11:45:00Z",
    comments: [
      { id: "c4", signalId: "s4", authorName: "Elena Martín", authorInitials: "EM", content: "Si escalan el entrenamiento automático, el horizonte se acerca mucho. Hay que seguir esta startup.", createdAt: "2026-05-09T13:00:00Z" },
    ],
  },
  {
    id: "s5",
    title: "67% de los jóvenes Z europeos elegiría menos sueldo a cambio de autonomía total sobre su tiempo",
    imageUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80",
    sources: [
      { label: "Eurofound — Future of Work Survey 2026", url: "https://www.eurofound.europa.eu" },
      { label: "Deloitte Global Millennial & Gen Z Survey 2026" },
      { label: "Harvard Business Review — The Sovereignty Economy" },
    ],
    observation: "Encuesta a 12.000 trabajadores menores de 30 años en 8 países europeos: el 67% prefiere un empleo con un 15% menos de salario si garantiza autonomía total sobre horarios y ubicación. El concepto de empresa como comunidad social está en declive acelerado.",
    whySignal: "El contrato social laboral del siglo XX —tiempo a cambio de dinero y seguridad— está siendo rechazado activamente por la generación que en 10 años dominará el mercado laboral. No es una preferencia marginal: es mayoritaria y crece cada año.",
    implication: "Si esto se consolida, el banco debe transformar radicalmente su propuesta de valor para atraer talento joven. Además, abre una oportunidad de producto: cuentas y herramientas financieras orientadas a la 'economía de la soberanía personal': ahorro por objetivos de vida, no por jubilación.",
    type: "social",
    strength: "strong",
    tags: [ALL_TAGS[2], ALL_TAGS[6], ALL_TAGS[8]],
    votes: 42,
    userVoted: false,
    authorName: "Lucía Fernández",
    authorInitials: "LF",
    createdAt: "2026-05-08T16:00:00Z",
    updatedAt: "2026-05-08T16:00:00Z",
    comments: [
      { id: "c5", signalId: "s5", authorName: "Carlos López", authorInitials: "CL", content: "Encaja con la señal del coworking distribuido. Hay un patrón claro emergiendo.", createdAt: "2026-05-09T09:00:00Z" },
      { id: "c6", signalId: "s5", authorName: "David Ruiz", authorInitials: "DR", content: "Tensión interesante con los modelos que aún requieren presencialidad para innovar.", createdAt: "2026-05-09T10:30:00Z" },
    ],
  },
  {
    id: "s6",
    title: "BCE lanza sandbox de euro digital programable para contratos de alquiler inteligentes",
    sources: [
      { label: "BCE Press Release, mayo 2026", url: "https://www.ecb.europa.eu" },
      { label: "Financial Times — CBDC European Pilot" },
    ],
    observation: "El Banco Central Europeo inicia un piloto con 500 hogares en Frankfurt y Lisboa: contratos de alquiler que usan euro digital con condiciones programables, ajustando automáticamente el pago según índices oficiales de referencia sin intervención bancaria.",
    whySignal: "Es la primera vez que dinero soberano incorpora lógica de contrato inteligente a escala real. Si escala, el dinero deja de ser pasivo y se convierte en un agente que ejecuta condiciones. Esto redefine el rol de los bancos como intermediarios en contratos financieros.",
    implication: "Si esto se extiende al sistema hipotecario, parte de la operativa bancaria tradicional queda desintermediada. El banco debe participar activamente en el sandbox antes de que se cierre el marco regulatorio, o arriesgarse a ser excluido del diseño de la infraestructura financiera del futuro.",
    type: "foresight",
    strength: "medium",
    tags: [ALL_TAGS[5], ALL_TAGS[4], ALL_TAGS[8]],
    votes: 15,
    userVoted: false,
    authorName: "Marta Sanz",
    authorInitials: "MS",
    createdAt: "2026-05-07T12:00:00Z",
    updatedAt: "2026-05-07T12:00:00Z",
    comments: [],
  },
  {
    id: "s7",
    title: "Primera promoción con currículo co-diseñado por IA se gradúa con 94% de empleabilidad",
    sources: [
      { label: "Times Higher Education, abril 2026", url: "https://www.timeshighereducation.com" },
      { label: "World Economic Forum — Future of Jobs 2026" },
    ],
    observation: "La primera cohorte de ingenieros formados bajo un currículo diseñado en colaboración con LLMs y actualizado trimestralmente tiene un 94% de inserción laboral a 6 meses. El currículo se revisó 11 veces en 4 años, frente a los ciclos estándar de 5-7 años.",
    whySignal: "La educación universitaria siempre ha tenido un problema de desfase entre lo que enseña y lo que demanda el mercado. La IA puede cerrar ese gap en tiempo real. Si este modelo escala, el título universitario deja de ser un certificado de conocimiento pasado y se convierte en una credencial dinámica.",
    implication: "Si esto se vuelve masivo, el banco captará talento con competencias más actualizadas pero menos estandarizadas. Oportunidad para establecer alianzas early con estas universidades y co-diseñar formación financiera del futuro, ganando ventaja en reclutamiento frente a competidores.",
    type: "article",
    strength: "medium",
    tags: [ALL_TAGS[0], ALL_TAGS[7], ALL_TAGS[9]],
    votes: 27,
    userVoted: false,
    authorName: "Isabel Gómez",
    authorInitials: "IG",
    createdAt: "2026-05-06T09:00:00Z",
    updatedAt: "2026-05-06T09:00:00Z",
    comments: [
      { id: "c7", signalId: "s7", authorName: "Ana Torres", authorInitials: "AT", content: "Clave el dato de empleabilidad. ¿Es causal o hay sesgo de selección en qué universidades adoptan esto?", createdAt: "2026-05-06T11:30:00Z" },
    ],
  },
  {
    id: "s8",
    title: "Movimiento 'Data Dignity' alcanza 3 millones de firmas para cobrar por el uso de datos personales",
    sources: [
      { label: "The Guardian, mayo 2026", url: "https://www.theguardian.com" },
      { label: "Wired — The Data Wage Movement" },
      { label: "Parlamento Europeo — Iniciativa ciudadana ECI #2847" },
    ],
    observation: "Una coalición ciudadana exige legislación que permita a individuos cobrar por el uso de sus datos en entrenamiento de modelos de IA. Ha recogido 3M de firmas en 30 días y cuenta con apoyo parlamentario explícito en Francia, Alemania, España y Países Bajos.",
    whySignal: "Hasta ahora, los datos personales eran un recurso extraído gratuitamente. Si esta iniciativa prospera, los datos se convierten en un activo con precio de mercado. Esto invierte la lógica económica de toda la industria tecnológica y redefine quién captura el valor en la economía de la atención.",
    implication: "Si prospera la legislación, el banco deberá revisar todos sus modelos de scoring, personalización y analítica basados en datos de clientes. También abre una ventana de diferenciación: ofrecer transparencia y control real sobre datos como propuesta de valor, antes de que sea obligatorio por ley.",
    type: "social",
    strength: "medium",
    tags: [ALL_TAGS[11], ALL_TAGS[4], ALL_TAGS[9]],
    votes: 33,
    userVoted: false,
    authorName: "Pablo Herrera",
    authorInitials: "PH",
    createdAt: "2026-05-05T14:00:00Z",
    updatedAt: "2026-05-05T14:00:00Z",
    comments: [],
  },

  // ── Infraestructura: Espacios Públicos & Transporte ──────────────────────
  {
    id: "s9",
    title: "Suecia abre la primera autopista con carga inalámbrica para vehículos eléctricos en movimiento",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    sources: [
      { label: "Trafikverket — Informe eRoadArlanda 2026", url: "https://www.trafikverket.se" },
      { label: "IEA — EV Infrastructure Outlook 2026" },
      { label: "Reuters Transport, abril 2026" },
    ],
    observation: "Suecia inaugura 20 km de autopista E20 con raíles de carga dinámica bajo el asfalto. Los vehículos compatibles cargan mientras circulan a 90 km/h. El coste por km de instalación cayó un 40% respecto al piloto de 2021. Noruega, Alemania y Corea del Sur han anunciado pilotos equivalentes.",
    whySignal: "Elimina la principal barrera de adopción del vehículo eléctrico: la ansiedad por autonomía. Si la infraestructura de carretera se electrifica, el concepto de 'batería grande' pierde sentido y el modelo de negocio del vehículo eléctrico se reorganiza alrededor de la suscripción a la red, no al hardware.",
    implication: "Si esto escala en Europa, las carteras de financiación de infraestructura deberán incorporar 'carretera como servicio' como nueva categoría de activo. Oportunidad de bono verde vinculado a kilómetros de vía electrificada. Riesgo para posiciones en fabricantes de baterías de gran capacidad.",
    type: "technology",
    strength: "strong",
    tags: [ALL_TAGS[12], ALL_TAGS[14], ALL_TAGS[1], ALL_TAGS[8]],
    votes: 38,
    userVoted: false,
    authorName: "David Ruiz",
    authorInitials: "DR",
    createdAt: "2026-05-13T08:00:00Z",
    updatedAt: "2026-05-13T08:00:00Z",
    comments: [
      { id: "c8", signalId: "s9", authorName: "Marta Sanz", authorInitials: "MS", content: "El modelo de suscripción a la vía cambia quién financia la infraestructura. Hay que rastrear cómo se estructura la concesión.", createdAt: "2026-05-13T09:30:00Z" },
      { id: "c9", signalId: "s9", authorName: "Carlos López", authorInitials: "CL", content: "Impacto directo en la valoración de activos de fabricantes de baterías en cartera. Lo paso al equipo de renta variable.", createdAt: "2026-05-13T11:00:00Z" },
    ],
  },
  {
    id: "s10",
    title: "Amsterdam elimina 11.000 plazas de aparcamiento para crear espacios públicos y carriles bici",
    imageUrl: "https://images.unsplash.com/photo-1601574968106-b312ac309953?w=800&q=80",
    sources: [
      { label: "Gemeente Amsterdam — Plan de Movilidad 2026-2030" },
      { label: "European Cyclists' Federation, mayo 2026" },
      { label: "The Guardian — Urban Futures, abril 2026", url: "https://www.theguardian.com" },
    ],
    observation: "Amsterdam ha eliminado 11.000 de sus 260.000 plazas de aparcamiento en superficie entre 2020 y 2026. El plan municipal prevé eliminar otras 10.000 antes de 2030. El espacio liberado se reconvierte en plazas verdes, carriles bici y terrazas. El precio del aparcamiento privado ha subido un 35% en 3 años.",
    whySignal: "No es un experimento: es política municipal consolidada en la ciudad más avanzada en movilidad urbana de Europa. Marca el camino que otras capitales europeas seguirán con un desfase de 5-8 años. El coche privado en el centro urbano pasa de norma a excepción regulada.",
    implication: "Las ciudades que repliquen este modelo generarán demanda masiva de aparcamiento subterráneo y periférico, y de soluciones de movilidad de último kilómetro. Oportunidad para financiar infraestructura de aparcamiento inteligente y proyectos de reconversión urbana como activos ESG.",
    type: "social",
    strength: "strong",
    tags: [ALL_TAGS[13], ALL_TAGS[10], ALL_TAGS[1], ALL_TAGS[8]],
    votes: 29,
    userVoted: false,
    authorName: "Elena Martín",
    authorInitials: "EM",
    createdAt: "2026-05-12T10:00:00Z",
    updatedAt: "2026-05-12T10:00:00Z",
    comments: [
      { id: "c10", signalId: "s10", authorName: "Isabel Gómez", authorInitials: "IG", content: "Madrid y Barcelona ya tienen planes similares en borrador. El timing es clave para financiar antes de que suba el coste del suelo.", createdAt: "2026-05-12T12:30:00Z" },
    ],
  },
  {
    id: "s11",
    title: "La IA predice colapsos de red de metro con 45 minutos de antelación en París",
    sources: [
      { label: "RATP — Innovation Report 2026" },
      { label: "MIT Mobility Initiative, marzo 2026", url: "https://mobility.mit.edu" },
    ],
    observation: "La red de metro de París implanta un sistema de IA que analiza en tiempo real datos de torniquetes, temperaturas, incidencias históricas y eventos urbanos. En pruebas durante 18 meses, predijo el 87% de los colapsos con 45 minutos de margen, permitiendo redistribuir trenes y activar rutas alternativas automáticamente.",
    whySignal: "Por primera vez, la gestión de infraestructura de transporte masivo pasa de reactiva a predictiva. El tiempo de respuesta ante una incidencia deja de medirse en horas y pasa a medirse en minutos. Esto cambia fundamentalmente el estándar de fiabilidad que ciudadanos y reguladores exigirán a las redes de transporte.",
    implication: "La adopción de IA predictiva en infraestructura pública crea un nuevo segmento de licitaciones municipales. Si el banco financia operadores de transporte, el ratio de adopción tecnológica debe entrar en los modelos de riesgo. Oportunidad de estructurar deuda verde ligada a métricas de eficiencia operativa.",
    type: "technology",
    strength: "medium",
    tags: [ALL_TAGS[0], ALL_TAGS[14], ALL_TAGS[15], ALL_TAGS[8]],
    votes: 21,
    userVoted: false,
    authorName: "Pablo Herrera",
    authorInitials: "PH",
    createdAt: "2026-05-11T09:00:00Z",
    updatedAt: "2026-05-11T09:00:00Z",
    comments: [
      { id: "c11", signalId: "s11", authorName: "Ana Torres", authorInitials: "AT", content: "El 87% de precisión es notable. ¿El modelo es propietario de la RATP o de un proveedor externo? Define quién captura el valor.", createdAt: "2026-05-11T10:45:00Z" },
    ],
  },
  {
    id: "s12",
    title: "Singapur despliega la primera red de autobuses autónomos sin conductor operativa 24h",
    imageUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&q=80",
    sources: [
      { label: "Land Transport Authority Singapore — AV Bus Report 2026" },
      { label: "Bloomberg CityLab, mayo 2026", url: "https://www.bloomberg.com/citylab" },
      { label: "WEF — Future of Urban Mobility 2026" },
    ],
    observation: "Singapur opera 12 rutas de autobús completamente autónomas en zonas urbanas y aeropuerto sin conductor de respaldo. Tarifa plana de 0,50 SGD (~0,35 €). Accidentalidad: 0 incidentes graves en 14 meses. La demanda superó la proyección en un 60% en el primer trimestre de operación real.",
    whySignal: "No es un piloto: es operación comercial real sin red de seguridad humana. Singapur demuestra que la autonomía total en transporte público masivo es técnica y legalmente viable hoy. El umbral de confianza pública, el mayor obstáculo hasta ahora, ha sido superado con datos reales de uso.",
    implication: "Si el modelo escala a Europa (horizonte 2029-2031), los operadores de transporte público deberán recapitalizarse para la transición tecnológica. Oportunidad de financiar esa transformación. Riesgo para posiciones en empresas de empleo de conductores o fabricantes de autobuses convencionales.",
    type: "foresight",
    strength: "strong",
    tags: [ALL_TAGS[14], ALL_TAGS[15], ALL_TAGS[12], ALL_TAGS[8]],
    votes: 44,
    userVoted: false,
    authorName: "Lucía Fernández",
    authorInitials: "LF",
    createdAt: "2026-05-10T11:00:00Z",
    updatedAt: "2026-05-10T11:00:00Z",
    comments: [
      { id: "c12", signalId: "s12", authorName: "David Ruiz", authorInitials: "DR", content: "La demanda 60% por encima de proyecciones invierte el argumento de 'la gente no va a subirse'. Hay que revisar nuestros supuestos sobre adopción.", createdAt: "2026-05-10T13:00:00Z" },
      { id: "c13", signalId: "s12", authorName: "Carlos López", authorInitials: "CL", content: "Impacto laboral brutal en el horizonte 2030-2035. ¿Cómo afecta a los sindicatos de transporte en España?", createdAt: "2026-05-10T14:30:00Z" },
    ],
  },
  {
    id: "s13",
    title: "Shenzhen convierte tejados industriales en parques elevados conectados por pasarelas",
    imageUrl: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&q=80",
    sources: [
      { label: "ArchDaily — Shenzhen Sky Park Network, 2026", url: "https://www.archdaily.com" },
      { label: "C40 Cities — Urban Heat Solutions Report 2026" },
      { label: "Nature Urban Sustainability, abril 2026" },
    ],
    observation: "Shenzhen ha conectado 34 tejados industriales con pasarelas peatonales y ciclistas, creando 18 km de espacio público elevado. Los 'sky parks' incluyen huertos urbanos, zonas de deporte y puntos de monitoreo medioambiental. Han reducido la temperatura de los barrios afectados entre 2 y 3 °C durante los picos de calor.",
    whySignal: "En ciudades donde el suelo en superficie es escaso o caro, el espacio público se crea en vertical. No es una propuesta arquitectónica: es una política de infraestructura que reclasifica los tejados como suelo público. El precedente legal y técnico está establecido y ya hay 8 ciudades asiáticas replicándolo.",
    implication: "Si este modelo llega a ciudades europeas densas (Barcelona, París, Milán), generará un nuevo mercado de financiación de infraestructura vertical de uso público. Los fondos de impacto urbano deberán incorporar esta tipología. Atractivo como activo ESG con métricas de reducción de calor urbano medibles.",
    type: "foresight",
    strength: "medium",
    tags: [ALL_TAGS[13], ALL_TAGS[1], ALL_TAGS[15], ALL_TAGS[8]],
    votes: 17,
    userVoted: false,
    authorName: "Marta Sanz",
    authorInitials: "MS",
    createdAt: "2026-05-09T10:00:00Z",
    updatedAt: "2026-05-09T10:00:00Z",
    comments: [],
  },
  {
    id: "s14",
    title: "El 68% de europeos elegiría transporte público si el tiempo de espera fuera inferior a 5 minutos",
    sources: [
      { label: "Eurobarometer — Urban Mobility Attitudes 2026" },
      { label: "UITP — Public Transport Demand Survey Q1 2026" },
      { label: "McKinsey — Cities at a Crossroads 2026" },
    ],
    observation: "Encuesta a 18.000 ciudadanos en 12 países europeos: el 68% afirma que dejaría el coche privado si el transporte público garantizara tiempos de espera menores a 5 minutos y cobertura de último kilómetro. El umbral cae al 45% si el tiempo de espera es de 10 minutos. La brecha entre intención y comportamiento real se estrecha cuando se mejora la frecuencia.",
    whySignal: "La barrera para abandonar el coche privado no es ideológica ni económica: es de fiabilidad y conveniencia. Este dato invierte la narrativa dominante. La demanda latente de transporte público de calidad es enorme, y la tecnología (predicción, frecuencia, último kilómetro) ya existe para capturarla.",
    implication: "Las ciudades que inviertan en frecuencia de servicio y cobertura de último kilómetro capturarán esa demanda latente. Oportunidad de financiar operadores de microtransporte urbano (e-buses de alta frecuencia, demand-responsive transit) como nueva categoría de infraestructura. El dato también refuerza la tesis de inversión en transporte público frente a infraestructura viaria.",
    type: "article",
    strength: "strong",
    tags: [ALL_TAGS[14], ALL_TAGS[10], ALL_TAGS[12], ALL_TAGS[8]],
    votes: 35,
    userVoted: false,
    authorName: "Ana Torres",
    authorInitials: "AT",
    createdAt: "2026-05-08T09:00:00Z",
    updatedAt: "2026-05-08T09:00:00Z",
    comments: [
      { id: "c14", signalId: "s14", authorName: "Elena Martín", authorInitials: "EM", content: "El dato del umbral de 5 vs 10 minutos es muy accionable. Hay que pasárselo al equipo de movilidad del cliente municipal.", createdAt: "2026-05-08T11:00:00Z" },
      { id: "c15", signalId: "s14", authorName: "Pablo Herrera", authorInitials: "PH", content: "Curioso que sea tan consistente entre países. Normalmente hay mucha varianza norte-sur.", createdAt: "2026-05-08T12:30:00Z" },
    ],
  },
];
