import { Signal, Tag } from "./types";

export const ALL_TAGS: Tag[] = [
  { id: "t1",  name: "IA Generativa",       color: "#8b5cf6", category: "technology" },
  { id: "t2",  name: "Sostenibilidad",       color: "#10b981", category: "theme" },
  { id: "t3",  name: "Trabajo Futuro",       color: "#f59e0b", category: "theme" },
  { id: "t4",  name: "Salud Digital",        color: "#ef4444", category: "sector" },
  { id: "t5",  name: "Geopolítica",          color: "#6366f1", category: "theme" },
  { id: "t6",  name: "Finanzas Descentralizadas", color: "#0ea5e9", category: "sector" },
  { id: "t7",  name: "Bienestar",            color: "#ec4899", category: "theme" },
  { id: "t8",  name: "Educación",            color: "#14b8a6", category: "sector" },
  { id: "t9",  name: "Horizonte 2030",       color: "#f97316", category: "horizon" },
  { id: "t10", name: "Horizonte 2040",       color: "#a855f7", category: "horizon" },
  { id: "t11", name: "Movilidad",            color: "#84cc16", category: "sector" },
  { id: "t12", name: "Privacidad",           color: "#64748b", category: "theme" },
];

export const MOCK_SIGNALS: Signal[] = [
  {
    id: "s1",
    title: "Los modelos de lenguaje comienzan a superar a expertos humanos en diagnóstico médico",
    description: "Estudios recientes muestran que LLMs entrenados con datos clínicos superan en un 12% la precisión diagnóstica de médicos residentes en patologías raras, abriendo debates sobre el rol del médico como intérprete de resultados.",
    url: "https://example.com/ai-medical",
    source: "Nature Medicine",
    type: "technology",
    strength: "strong",
    tags: [ALL_TAGS[0], ALL_TAGS[3], ALL_TAGS[8]],
    votes: 24,
    userVoted: false,
    authorName: "Elena Martín",
    authorInitials: "EM",
    createdAt: "2026-05-12T09:30:00Z",
    updatedAt: "2026-05-12T09:30:00Z",
    comments: [
      {
        id: "c1", signalId: "s1",
        authorName: "Carlos López", authorInitials: "CL",
        content: "Interesante señal. Habría que cruzarla con las tendencias regulatorias en la UE sobre IA médica.",
        createdAt: "2026-05-12T10:15:00Z",
      },
      {
        id: "c2", signalId: "s1",
        authorName: "Ana Torres", authorInitials: "AT",
        content: "El 12% es estadísticamente significativo pero el contexto importa mucho. ¿Solo residentes o también especialistas?",
        createdAt: "2026-05-12T11:00:00Z",
      },
    ],
  },
  {
    id: "s2",
    title: "Primeras ciudades europeas prohíben vuelos de corta distancia con alternativa ferroviaria",
    description: "Francia extiende su prohibición de vuelos domésticos a rutas con tren de menos de 4 horas. Otros 6 países están debatiendo legislación similar, impactando directamente la industria aérea de corto radio.",
    source: "Le Monde / Reuters",
    type: "social",
    strength: "strong",
    tags: [ALL_TAGS[1], ALL_TAGS[4], ALL_TAGS[10], ALL_TAGS[8]],
    votes: 31,
    userVoted: true,
    authorName: "David Ruiz",
    authorInitials: "DR",
    createdAt: "2026-05-11T14:20:00Z",
    updatedAt: "2026-05-11T14:20:00Z",
    comments: [
      {
        id: "c3", signalId: "s2",
        authorName: "Isabel Gómez", authorInitials: "IG",
        content: "Señal importante para el sector turístico también. Los patrones de viaje van a cambiar radicalmente.",
        createdAt: "2026-05-11T16:30:00Z",
      },
    ],
  },
  {
    id: "s3",
    title: "El 40% de los freelancers globales usan IA como 'empleado virtual' principal",
    description: "Un estudio de Upwork revela que el colectivo freelance ha adoptado masivamente herramientas de IA para subcontratar tareas cognitivas, creando una nueva capa de 'economía aumentada' que difumina los límites del trabajo humano.",
    source: "Upwork Future Workforce Report",
    type: "foresight",
    strength: "medium",
    tags: [ALL_TAGS[0], ALL_TAGS[2], ALL_TAGS[8]],
    votes: 18,
    userVoted: false,
    authorName: "Marta Sanz",
    authorInitials: "MS",
    createdAt: "2026-05-10T08:00:00Z",
    updatedAt: "2026-05-10T08:00:00Z",
    comments: [],
  },
  {
    id: "s4",
    title: "Nuevas interfaces neuronales no invasivas alcanzan 200 palabras por minuto",
    description: "Startup californiana logra tasa de transcripción de pensamiento a texto de 200 wpm con un headband EEG de consumo. La interfaz aún requiere entrenamiento personalizado pero es viable sin cirugía.",
    source: "MIT Technology Review",
    type: "technology",
    strength: "weak",
    tags: [ALL_TAGS[0], ALL_TAGS[3], ALL_TAGS[9]],
    votes: 9,
    userVoted: false,
    authorName: "Pablo Herrera",
    authorInitials: "PH",
    createdAt: "2026-05-09T11:45:00Z",
    updatedAt: "2026-05-09T11:45:00Z",
    comments: [
      {
        id: "c4", signalId: "s4",
        authorName: "Elena Martín", authorInitials: "EM",
        content: "Hay que seguir esta startup. Si escalan el entrenamiento automático, el horizonte se acerca mucho.",
        createdAt: "2026-05-09T13:00:00Z",
      },
    ],
  },
  {
    id: "s5",
    title: "Jóvenes Z priorizan 'tiempo soberano' sobre salario en decisiones laborales",
    description: "Encuesta europea de 12.000 trabajadores menores de 30 años muestra que el 67% elegiría un empleo con un 15% menos de sueldo si garantiza autonomía total sobre horarios y localización. El modelo de empresa como espacio social está en declive.",
    source: "Eurofound 2026",
    type: "social",
    strength: "strong",
    tags: [ALL_TAGS[2], ALL_TAGS[6], ALL_TAGS[8]],
    votes: 42,
    userVoted: false,
    authorName: "Lucía Fernández",
    authorInitials: "LF",
    createdAt: "2026-05-08T16:00:00Z",
    updatedAt: "2026-05-08T16:00:00Z",
    comments: [
      {
        id: "c5", signalId: "s5",
        authorName: "Carlos López", authorInitials: "CL",
        content: "Esto encaja con la señal del coworking distribuido que vimos el mes pasado.",
        createdAt: "2026-05-09T09:00:00Z",
      },
      {
        id: "c6", signalId: "s5",
        authorName: "David Ruiz", authorInitials: "DR",
        content: "Interesante tensión con los modelos de empresa que aún requieren presencialidad para innovar.",
        createdAt: "2026-05-09T10:30:00Z",
      },
    ],
  },
  {
    id: "s6",
    title: "Banco Central Europeo lanza sandbox de CBDC programable para contratos de vivienda",
    description: "El BCE inicia prueba piloto de euro digital con condiciones programables: contratos de alquiler inteligentes que ajustan automáticamente el pago según índices de referencia. Primeros 500 hogares en Frankfurt y Lisboa.",
    source: "BCE Press Release",
    type: "foresight",
    strength: "medium",
    tags: [ALL_TAGS[5], ALL_TAGS[4], ALL_TAGS[8]],
    votes: 15,
    userVoted: false,
    authorName: "Marta Sanz",
    authorInitials: "MS",
    createdAt: "2026-05-07T12:00:00Z",
    updatedAt: "2026-05-07T12:00:00Z",
    comments: [],
  },
  {
    id: "s7",
    title: "Primeras titulaciones universitarias co-diseñadas con IA se gradúan con empleabilidad récord",
    description: "La primera promoción de ingenieros formados bajo un currículo diseñado en colaboración con LLMs y actualizado en tiempo real tiene un 94% de inserción laboral a 6 meses. El modelo podría reemplazar los ciclos de revisión curricular de 5 años.",
    source: "Times Higher Education",
    type: "article",
    strength: "medium",
    tags: [ALL_TAGS[0], ALL_TAGS[7], ALL_TAGS[9]],
    votes: 27,
    userVoted: false,
    authorName: "Isabel Gómez",
    authorInitials: "IG",
    createdAt: "2026-05-06T09:00:00Z",
    updatedAt: "2026-05-06T09:00:00Z",
    comments: [
      {
        id: "c7", signalId: "s7",
        authorName: "Ana Torres", authorInitials: "AT",
        content: "Clave el dato de empleabilidad. Hay que vigilar cómo se mide y si es causal o correlacional.",
        createdAt: "2026-05-06T11:30:00Z",
      },
    ],
  },
  {
    id: "s8",
    title: "Movimiento 'Data Dignity' alcanza 3M de firmas para monetización personal de datos",
    description: "Una coalición ciudadana exige legislación que permita a individuos cobrar por el uso de sus datos en entrenamiento de IA. El movimiento ha logrado apoyo parlamentario en 4 países y podría cambiar radicalmente el modelo de negocio de big tech.",
    source: "The Guardian / Wired",
    type: "social",
    strength: "medium",
    tags: [ALL_TAGS[11], ALL_TAGS[4], ALL_TAGS[9]],
    votes: 33,
    userVoted: false,
    authorName: "Pablo Herrera",
    authorInitials: "PH",
    createdAt: "2026-05-05T14:00:00Z",
    updatedAt: "2026-05-05T14:00:00Z",
    comments: [],
  },
];
