import { Signal, Tag } from "./types";

export const ALL_TAGS: Tag[] = [
  { id: "t1",  name: "IA Generativa",            color: "#8b5cf6", category: "technology" },
  { id: "t2",  name: "Sostenibilidad",            color: "#10b981", category: "theme" },
  { id: "t3",  name: "Trabajo Futuro",            color: "#f59e0b", category: "theme" },
  { id: "t4",  name: "Salud Digital",             color: "#ef4444", category: "sector" },
  { id: "t5",  name: "Geopolítica",               color: "#6366f1", category: "theme" },
  { id: "t6",  name: "Finanzas Descentralizadas", color: "#0ea5e9", category: "sector" },
  { id: "t7",  name: "Bienestar",                 color: "#ec4899", category: "theme" },
  { id: "t8",  name: "Educación",                 color: "#14b8a6", category: "sector" },
  { id: "t9",  name: "Horizonte 2030",            color: "#f97316", category: "horizon" },
  { id: "t10", name: "Horizonte 2040",            color: "#a855f7", category: "horizon" },
  { id: "t11", name: "Movilidad",                 color: "#84cc16", category: "sector" },
  { id: "t12", name: "Privacidad",                color: "#64748b", category: "theme" },
];

export const MOCK_SIGNALS: Signal[] = [
  {
    id: "s1",
    title: "LLMs superan a médicos residentes en diagnóstico de patologías raras",
    sources: [
      { label: "Nature Medicine, 2026", url: "https://www.nature.com/nm" },
      { label: "Stanford HAI Report 2025", url: "https://hai.stanford.edu" },
    ],
    observation: "Modelos de lenguaje entrenados con datos clínicos superan en un 12% la precisión diagnóstica de médicos residentes en enfermedades raras. El estudio abarca 14 hospitales en 6 países y 80.000 casos.",
    whySignal: "Por primera vez, la IA no asiste al médico: lo supera en una tarea cognitiva nuclear. Esto rompe el paradigma de la IA como herramienta de apoyo y plantea un nuevo rol para el profesional sanitario como intérprete y validador, no como diagnosticador primario.",
    implication: "Si esto se vuelve masivo, el banco deberá revisar sus productos de seguro de salud y la valoración de activos en clínicas. Abre además una oportunidad de financiación verde para hospitales que adopten IA diagnóstica, con impacto directo en la cartera de crédito corporativo del sector salud.",
    type: "technology",
    strength: "strong",
    tags: [ALL_TAGS[0], ALL_TAGS[3], ALL_TAGS[8]],
    votes: 24,
    userVoted: false,
    authorName: "Elena Martín",
    authorInitials: "EM",
    createdAt: "2026-05-12T09:30:00Z",
    updatedAt: "2026-05-12T09:30:00Z",
    comments: [
      { id: "c1", signalId: "s1", authorName: "Carlos López", authorInitials: "CL", content: "Habría que cruzarla con las tendencias regulatorias en la UE sobre IA médica.", createdAt: "2026-05-12T10:15:00Z" },
      { id: "c2", signalId: "s1", authorName: "Ana Torres", authorInitials: "AT", content: "El 12% es significativo pero el contexto importa. ¿Solo residentes o también especialistas?", createdAt: "2026-05-12T11:00:00Z" },
    ],
  },
  {
    id: "s2",
    title: "Francia prohíbe vuelos domésticos con alternativa ferroviaria inferior a 4 horas",
    sources: [
      { label: "Le Monde, abril 2026", url: "https://www.lemonde.fr" },
      { label: "Reuters Climate Policy Tracker" },
      { label: "Comisión Europea — Directiva de movilidad sostenible" },
    ],
    observation: "Francia amplía su veto a vuelos domésticos a todas las rutas con tren de menos de 4 horas. Otros 6 países europeos debaten legislación equivalente. Afecta a más de 40 rutas y 12 millones de pasajeros anuales.",
    whySignal: "No es una medida voluntaria ni un incentivo fiscal: es una prohibición directa. Marca el inicio de una regulación punitiva sobre la movilidad de alto carbono, algo inédito en democracias occidentales. La presión política para extenderlo a nivel europeo crece rápidamente.",
    implication: "Si esto se extiende a toda la UE, el banco deberá provisionar riesgo en su cartera de financiación a aerolíneas regionales y aeropuertos. Simultáneamente, se abren oportunidades concretas de bono verde para infraestructura ferroviaria y productos de inversión ESG vinculados a movilidad baja en carbono.",
    type: "social",
    strength: "strong",
    tags: [ALL_TAGS[1], ALL_TAGS[4], ALL_TAGS[10], ALL_TAGS[8]],
    votes: 31,
    userVoted: true,
    authorName: "David Ruiz",
    authorInitials: "DR",
    createdAt: "2026-05-11T14:20:00Z",
    updatedAt: "2026-05-11T14:20:00Z",
    comments: [
      { id: "c3", signalId: "s2", authorName: "Isabel Gómez", authorInitials: "IG", content: "Los patrones de viaje de negocio van a cambiar radicalmente. Impacto en las tarjetas corporate.", createdAt: "2026-05-11T16:30:00Z" },
    ],
  },
  {
    id: "s3",
    title: "El 40% de los freelancers globales usan IA como su 'empleado virtual' principal",
    sources: [
      { label: "Upwork Future Workforce Report 2026", url: "https://www.upwork.com/research" },
      { label: "McKinsey Global Institute — The Augmented Worker" },
    ],
    observation: "Upwork documenta que 4 de cada 10 trabajadores independientes delegan sistemáticamente tareas cognitivas a herramientas de IA, facturando hasta un 60% más sin aumentar sus horas trabajadas. Emerge una nueva clase: el trabajador aumentado.",
    whySignal: "La IA ya no es una ventaja competitiva para el freelancer: es infraestructura básica. Esto crea una bifurcación brutal en el mercado laboral entre quienes la adoptan y quienes no, y difumina la frontera entre trabajo humano y automatizado en la economía de servicios.",
    implication: "Si esto se vuelve masivo, el modelo de scoring crediticio para autónomos queda obsoleto. El banco debe rediseñar sus productos de financiación para el trabajador aumentado: ingresos más volátiles pero con mayor capacidad de escala, algo que los modelos actuales de riesgo no capturan.",
    type: "foresight",
    strength: "medium",
    tags: [ALL_TAGS[0], ALL_TAGS[2], ALL_TAGS[8]],
    votes: 18,
    userVoted: false,
    authorName: "Marta Sanz",
    authorInitials: "MS",
    createdAt: "2026-05-10T08:00:00Z",
    updatedAt: "2026-05-10T08:00:00Z",
    comments: [],
  },
  {
    id: "s4",
    title: "Interfaces neuronales no invasivas alcanzan 200 palabras por minuto sin cirugía",
    sources: [
      { label: "MIT Technology Review, marzo 2026", url: "https://www.technologyreview.com" },
      { label: "Neurosity — EEG Consumer Report" },
    ],
    observation: "Una startup californiana logra transcribir pensamiento a texto a 200 palabras por minuto usando un headband EEG de consumo. Requiere entrenamiento personal de 2 horas. Precio estimado de lanzamiento: 400 USD.",
    whySignal: "Elimina la barrera quirúrgica de las interfaces neuronales. Por primera vez existe un camino realista hacia la interacción humano-ordenador sin pantalla ni teclado, accesible al consumidor masivo. La curva de adopción podría ser más rápida que la del smartphone.",
    implication: "Si esto se vuelve masivo en 2035-2040, el banco deberá rediseñar toda su UX desde cero. La autenticación biométrica neural podría reemplazar contraseñas y biometría facial. Señal de vigilancia estratégica: invertir hoy en explorar aplicaciones para banca sin fricción.",
    type: "technology",
    strength: "weak",
    tags: [ALL_TAGS[0], ALL_TAGS[3], ALL_TAGS[9]],
    votes: 9,
    userVoted: false,
    authorName: "Pablo Herrera",
    authorInitials: "PH",
    createdAt: "2026-05-09T11:45:00Z",
    updatedAt: "2026-05-09T11:45:00Z",
    comments: [
      { id: "c4", signalId: "s4", authorName: "Elena Martín", authorInitials: "EM", content: "Si escalan el entrenamiento automático, el horizonte se acerca mucho. Hay que seguir esta startup.", createdAt: "2026-05-09T13:00:00Z" },
    ],
  },
  {
    id: "s5",
    title: "67% de los jóvenes Z europeos elegiría menos sueldo a cambio de autonomía total sobre su tiempo",
    sources: [
      { label: "Eurofound — Future of Work Survey 2026", url: "https://www.eurofound.europa.eu" },
      { label: "Deloitte Global Millennial & Gen Z Survey 2026" },
      { label: "Harvard Business Review — The Sovereignty Economy" },
    ],
    observation: "Encuesta a 12.000 trabajadores menores de 30 años en 8 países europeos: el 67% prefiere un empleo con un 15% menos de salario si garantiza autonomía total sobre horarios y ubicación. El concepto de empresa como comunidad social está en declive acelerado.",
    whySignal: "El contrato social laboral del siglo XX —tiempo a cambio de dinero y seguridad— está siendo rechazado activamente por la generación que en 10 años dominará el mercado laboral. No es una preferencia marginal: es mayoritaria y crece cada año.",
    implication: "Si esto se consolida, el banco debe transformar radicalmente su propuesta de valor para atraer talento joven. Además, abre una oportunidad de producto: cuentas y herramientas financieras orientadas a la 'economía de la soberanía personal': ahorro por objetivos de vida, no por jubilación.",
    type: "social",
    strength: "strong",
    tags: [ALL_TAGS[2], ALL_TAGS[6], ALL_TAGS[8]],
    votes: 42,
    userVoted: false,
    authorName: "Lucía Fernández",
    authorInitials: "LF",
    createdAt: "2026-05-08T16:00:00Z",
    updatedAt: "2026-05-08T16:00:00Z",
    comments: [
      { id: "c5", signalId: "s5", authorName: "Carlos López", authorInitials: "CL", content: "Encaja con la señal del coworking distribuido. Hay un patrón claro emergiendo.", createdAt: "2026-05-09T09:00:00Z" },
      { id: "c6", signalId: "s5", authorName: "David Ruiz", authorInitials: "DR", content: "Tensión interesante con los modelos que aún requieren presencialidad para innovar.", createdAt: "2026-05-09T10:30:00Z" },
    ],
  },
  {
    id: "s6",
    title: "BCE lanza sandbox de euro digital programable para contratos de alquiler inteligentes",
    sources: [
      { label: "BCE Press Release, mayo 2026", url: "https://www.ecb.europa.eu" },
      { label: "Financial Times — CBDC European Pilot" },
    ],
    observation: "El Banco Central Europeo inicia un piloto con 500 hogares en Frankfurt y Lisboa: contratos de alquiler que usan euro digital con condiciones programables, ajustando automáticamente el pago según índices oficiales de referencia sin intervención bancaria.",
    whySignal: "Es la primera vez que dinero soberano incorpora lógica de contrato inteligente a escala real. Si escala, el dinero deja de ser pasivo y se convierte en un agente que ejecuta condiciones. Esto redefine el rol de los bancos como intermediarios en contratos financieros.",
    implication: "Si esto se extiende al sistema hipotecario, parte de la operativa bancaria tradicional queda desintermediada. El banco debe participar activamente en el sandbox antes de que se cierre el marco regulatorio, o arriesgarse a ser excluido del diseño de la infraestructura financiera del futuro.",
    type: "foresight",
    strength: "medium",
    tags: [ALL_TAGS[5], ALL_TAGS[4], ALL_TAGS[8]],
    votes: 15,
    userVoted: false,
    authorName: "Marta Sanz",
    authorInitials: "MS",
    createdAt: "2026-05-07T12:00:00Z",
    updatedAt: "2026-05-07T12:00:00Z",
    comments: [],
  },
  {
    id: "s7",
    title: "Primera promoción con currículo co-diseñado por IA se gradúa con 94% de empleabilidad",
    sources: [
      { label: "Times Higher Education, abril 2026", url: "https://www.timeshighereducation.com" },
      { label: "World Economic Forum — Future of Jobs 2026" },
    ],
    observation: "La primera cohorte de ingenieros formados bajo un currículo diseñado en colaboración con LLMs y actualizado trimestralmente tiene un 94% de inserción laboral a 6 meses. El currículo se revisó 11 veces en 4 años, frente a los ciclos estándar de 5-7 años.",
    whySignal: "La educación universitaria siempre ha tenido un problema de desfase entre lo que enseña y lo que demanda el mercado. La IA puede cerrar ese gap en tiempo real. Si este modelo escala, el título universitario deja de ser un certificado de conocimiento pasado y se convierte en una credencial dinámica.",
    implication: "Si esto se vuelve masivo, el banco captará talento con competencias más actualizadas pero menos estandarizadas. Oportunidad para establecer alianzas early con estas universidades y co-diseñar formación financiera del futuro, ganando ventaja en reclutamiento frente a competidores.",
    type: "article",
    strength: "medium",
    tags: [ALL_TAGS[0], ALL_TAGS[7], ALL_TAGS[9]],
    votes: 27,
    userVoted: false,
    authorName: "Isabel Gómez",
    authorInitials: "IG",
    createdAt: "2026-05-06T09:00:00Z",
    updatedAt: "2026-05-06T09:00:00Z",
    comments: [
      { id: "c7", signalId: "s7", authorName: "Ana Torres", authorInitials: "AT", content: "Clave el dato de empleabilidad. ¿Es causal o hay sesgo de selección en qué universidades adoptan esto?", createdAt: "2026-05-06T11:30:00Z" },
    ],
  },
  {
    id: "s8",
    title: "Movimiento 'Data Dignity' alcanza 3 millones de firmas para cobrar por el uso de datos personales",
    sources: [
      { label: "The Guardian, mayo 2026", url: "https://www.theguardian.com" },
      { label: "Wired — The Data Wage Movement" },
      { label: "Parlamento Europeo — Iniciativa ciudadana ECI #2847" },
    ],
    observation: "Una coalición ciudadana exige legislación que permita a individuos cobrar por el uso de sus datos en entrenamiento de modelos de IA. Ha recogido 3M de firmas en 30 días y cuenta con apoyo parlamentario explícito en Francia, Alemania, España y Países Bajos.",
    whySignal: "Hasta ahora, los datos personales eran un recurso extraído gratuitamente. Si esta iniciativa prospera, los datos se convierten en un activo con precio de mercado. Esto invierte la lógica económica de toda la industria tecnológica y redefine quién captura el valor en la economía de la atención.",
    implication: "Si prospera la legislación, el banco deberá revisar todos sus modelos de scoring, personalización y analítica basados en datos de clientes. También abre una ventana de diferenciación: ofrecer transparencia y control real sobre datos como propuesta de valor, antes de que sea obligatorio por ley.",
    type: "social",
    strength: "medium",
    tags: [ALL_TAGS[11], ALL_TAGS[4], ALL_TAGS[9]],
    votes: 33,
    userVoted: false,
    authorName: "Pablo Herrera",
    authorInitials: "PH",
    createdAt: "2026-05-05T14:00:00Z",
    updatedAt: "2026-05-05T14:00:00Z",
    comments: [],
  },
];
